x = float(input("Informe quanto custava o salgado:"))
w = float(input("Informe quanto custa o salgado:"))
v = float(input("Quanto dinheiro vc tem? "))
h = int(v / x)
d = int(v / w)
print("Com esse dinheiro vc compraria " + str(h) + "Salgados")
print("Com esse dinheiro vc compra " + str(d) + "salgados")
