x = float(input("informe quanto o salgado custava:"))
w = float(input("informe quanto o salgado custa:"))
v = float(input("quanto dinheiro você tem :"))
h = int(v / x)
d = int(v / w)
print("com esse dinheiro você comprava " + str(h) + " salgados")
print("com esse diheiro você compra " + str(d) + " salgados") 
