x = float(input("informe quanto o salgado custava:"))
w = float(input("informe quanto o salgado custa:"))
v = float(input("quanto dinheiro vc tem :"))
h = int(v / x)
d = int(v / w)
print("com esse dinheiro voce compravra " + str(h) + " salgados")
print("com esse dinheiro voce compra " + str(d) + " salgados")
